# Generated by Django 5.0.1 on 2024-02-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TogriSoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NotogriSoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=30)),
                ('t_soz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.togrisoz')),
            ],
        ),
    ]
